version: '3'
services: 
  postgres: 
    image: 'postgres:latest'
    container_name: '<containername>'

    environment:
      POSTGRES_USER: '<user>'
      POSTGRES_PASSWORD: '<password>'
      POSTGRES_DB: '<db_name>'

    ports: 
      - '<defaultport>:5432'